#+title: Readme
* Dynamic Programming
Technique were you store/cache computations into a data structure (typically an array) and then reuse them to compute the next step of the function.

There are two kind of dynamic programming.

1. Top-down approach: memoization
2. Bottom-up: Tabulation.

* Problems:
** [[https://leetcode.com/problems/maximum-subarray/description/][53. Maximum Subarray]]

This is one of the suggested problems in Grind 75 problemset. I found it a little bit complicated to reason on my own.

#+BEGIN_SRC python
class Solution:
    def maxSubArray(self, nums: List[int]) -> int:
        partialMaxSubArraySum = [nums[0]]
        for i in range(1,len(nums)):
            partialMaxSubArraySum.append(
                max(partialMaxSubArraySum[-1] + nums[i], nums[i])
            )
        return max(partialMaxSubArraySum)
#+END_SRC

The intuition behind this algorithm is simple. We use an array for the dynamic programming aspect of it.

At every index i we want to store the maximum sum that you can calculate from array nums whose last index is i. Later we calculate max over the whole array.

More deeply at every index the largest subarray for an array that ends up in that index is either adding the current number to the max sum of the element in the left or if that's a negative number it's always better to restart a group.


