#+title: Dynamic Programming
Technique were you store/cache computations into a data structure (typically an array) and then reuse them to compute the next step of the function.

There are two kind of dynamic programming.

1. Top-down approach: memoization
2. Bottom-up: Tabulation.

* Problems:
** [[https://leetcode.com/problems/maximum-subarray/description/][53. Maximum Subarray]]

This is one of the suggested problems in Grind 75 problemset. I found it a little bit complicated to reason on my own.

#+BEGIN_SRC python
class Solution:
    def maxSubArray(self, nums: List[int]) -> int:
        partialMaxSubArraySum = [nums[0]]
        for i in range(1,len(nums)):
            partialMaxSubArraySum.append(
                max(partialMaxSubArraySum[-1] + nums[i], nums[i])
            )
        return max(partialMaxSubArraySum)
#+END_SRC

The intuition behind this algorithm is simple. We use an array for the dynamic programming aspect of it.

At every index i we want to store the maximum sum that you can calculate from array nums whose last index is i. Later we calculate max over the whole array.

More deeply at every index the largest subarray for an array that ends up in that index is either adding the current number to the max sum of the element in the left or if that's a negative number it's always better to restart a group.
** [[https://leetcode.com/problems/01-matrix/description/][01 Matrix]]

After submitting my answer for 01 matrix I discovered that it was slower than 95% of all answers. This was pretty disappointing since my BFS was a linear algorithm.

I then saw that there was a better answer that involves traversing the matrix two times and gives you the result in place.

The intuition behind this solution is that the final result for each of the elements in the resulting matrix will come from a two directions path in the matrix. For that reason we traverse the matrix from the top left corner into the bottom right corner and at every point we try to calculate the distance to that point to a zero by updating the value with the min(left, up) + 1.

That would give us for every point the closest zero that they have in their upper left section i.e.

#+BEGIN_SRC python
# 0 1 2 3 4
# 1 2 3 4 5
# 2 3 0 1 2
# 3 4 1 2 3
#+END_SRC

Then we traverse it from the bottom right corner following the inverse steps and doing a similar update.

It is clear that for every element if the closest zero was in either it's upper-left corner or bottom-right corner we would have it as a consequence of having calculated each of the points as the min of left, up and right, bottom respectively.

What is less clear is that if the closest zero was in the upper-right or bottom-left we are taking that into account...

Since the second pass happens over an already transformed matrix for every element all of the elements on it's RHS they already contain the minimum distance to any zero on top of them.

With a similar argument one can prove that this also happens to those in the bottom-left.

The solution is really cool. Credits to Mayowa Daniel that left a very nice [[https://leetcode.com/problems/01-matrix/description/][video in the comments]].

#+BEGIN_SRC python
class Solution:
    def updateMatrixTopLeft(self, mat: List[List[int]], n: int, m: int) -> List[List[int]]:
        for i in range(n):
            for j in range(m):
                if mat[i][j] > 0:
                    up = mat[i-1][j] if i > 0 else math.inf

                    left = mat[i][j-1] if j > 0 else math.inf

                    mat[i][j] = min(up, left) + 1

    def updateMatrixBottomRight(self, mat: List[List[int]], n: int, m: int) -> List[List[int]]:
        for i in reversed(range(n)):
            for j in reversed(range(m)):
                if mat[i][j] > 0:
                    down = mat[i+1][j] if i+1 < n else math.inf

                    right = mat[i][j+1] if j+1 < m else math.inf

                    mat[i][j] = min(mat[i][j], min(down, right) + 1)

    def updateMatrix(self, mat: List[List[int]]) -> List[List[int]]:
        n = len(mat)
        m = len(mat[0])

        self.updateMatrixTopLeft(mat, n, m)

        self.updateMatrixBottomRight(mat, n, m)

        return mat  
#+END_SRC
** [[https://leetcode.com/problems/coin-change/description/][322. Coin Change]]
I started to work on this problem using a Greedy approach plus some minor optimizations (e.g. binary search not to calculate the complete decomposition each time).
However after some time limit exceptions I saw a comment that showed me that the greedy algorithm is not always the most useful (e.g. 25 + 10 + 5 vs 20 + 20). After reading the [[https://en.wikipedia.org/wiki/Change-making_problem][wikipedia article]] I found the original paper where they discuss the motivation behind the dynamic programming algorithm ([[https://dl.acm.org/doi/epdf/10.1145/321864.321874][worth reading]]).

In the end I just used the provided solution in wikipedia. I cannot say I learnt a lot from this submission however it was nice understanding the paper.

#+BEGIN_SRC python
def start_coin_change_memo(coins, amount):
    coin_change_memo = [
        [0 for _ in range(amount + 1)]
        for _ in range(len(coins)+1)
    ]
    for r in range(1, amount+1):
        coin_change_memo[0][r] = math.inf
    return coin_change_memo

class Solution:
    def coinChange(self, coins: List[int], amount: int) -> int:
        memo = start_coin_change_memo(coins, amount)

        for c, coin in enumerate(coins, 1):
            for r in range(1, amount + 1):
                # If the number we want to add up to can be done using the coin use it.
                if coin == r:
                    memo[c][r] = 1
                # If we cannot use the coin because it's too big we try to complete r using coins smaller than r.
                if coin > r:
                    memo[c][r] = memo[c-1][r]
                else:
                    memo[c][r] = min(memo[c-1][r], 1 + memo[c][r-coin])
        
        return memo[-1][-1] if memo[-1][-1] != math.inf else -1
#+END_SRC
** [[https://leetcode.com/problems/partition-equal-subset-sum/][416. Partition Equal Subset Sum]]
This problem can be reduced into [[https://www.geeksforgeeks.org/dsa/0-1-knapsack-problem-dp-10/][the 0/1 knapsack problem]]. The way we can do this is by following this observation. Partitioning the input array would happen if the sum of all of it's numbers can be divided evenly in two that is to say that we can have a subset of the numbers that adds up to the same amount as the other subset. Hence the total sum of nums must be 2*sum where sum is the sum of each partition. A way to proceed would be to add up all the numbers in the input array and verify if the sum is even then we can try and solve the 0/1 knapsack problem for knapsack of size sum and if it returns sum we are sure that the partition can happen.

#+BEGIN_SRC python
class Solution:
    def knapsack_bottom_up(self, w, nums):
        memo = [[0]*(w + 1) for _ in range(len(nums)+1)]

        for i in range(1, len(nums)+1):
            for j in range(1, w+1):
                pick = 0

                if nums[i-1] <= j:
                    pick = nums[i-1] + memo[i-1][j-nums[i-1]]
                
                not_pick = memo[i-1][j]

                memo[i][j] = max(pick, not_pick)
        
        return memo[len(nums)][w]

    def canPartition(self, nums: List[int]) -> bool:
        sum_all_numbers = sum(nums)
        if sum_all_numbers%2:
            return False
        
        target_sum = sum_all_numbers//2

        return self.knapsack_bottom_up(target_sum, nums) == target_sum
#+END_SRC
