#+title: DFS traversal
In this sort of problems we need to prioritize exploring the tree in depth instead of in breadth for that what we use is a stack (i.e. fifo traversal).
* Problems:
** [[https://leetcode.com/problems/diameter-of-binary-tree/description/][543. Diameter of Binary Tree]]

To complete this problem I performed a postorder traversal of the binary tree using two stacks. Did this for memory optimization we won't have stack overflow due to recursion.

In the second while (the postorder while) we do two things: 1 calculate the heights of both subtrees 2. try to verify if the current difference between max lengths of bothe subtrees is greater than the current diameter.

#+BEGIN_SRC python
class Solution:
    def diameterOfBinaryTree(self, root: Optional[TreeNode]) -> int:
        stack1 = [root]
        stack2 = []
        longest_path_between_two_nodes = 0

        while stack1:
            current_node = stack1.pop()
            stack2.append(current_node)
            if current_node.left:
                stack1.append(current_node.left)
            if current_node.right:
                stack1.append(current_node.right)
        
        while stack2:
            current_node = stack2.pop()
            left_subtree_height = current_node.left.val + 1 if current_node.left else 0
            right_subtree_height = current_node.right.val + 1 if current_node.right else 0
            current_node.val = max(left_subtree_height, right_subtree_height)
            longest_path_between_two_nodes = max(longest_path_between_two_nodes, left_subtree_height + right_subtree_height)
        
        return longest_path_between_two_nodes
#+END_SRC
** [[https://leetcode.com/problems/validate-binary-search-tree/][98. Validate Binary Search Tree]]

To complete this problem I traversed the BST recursively in a DFS fashion. At each point we compare the current value with the min value and max value that has been seen in that branch of the tree. If at some point we see that the current value is greater or equal than the max value of the the explored tree up until that point we return false. If at asome point we see that the converse statement is true (i.e. that the current value is less or equal than the minimum value of the explored tree up until that point).

Last but not least we check that the left and right subtrees are also valid. We use the current value as the maximum value expected for the left subtree and as the minimum for the right subtree.

#+BEGIN_SRC python
# Definition for a binary tree node.
# class TreeNode:
#     def __init__(self, val=0, left=None, right=None):
#         self.val = val
#         self.left = left
#         self.right = right
class Solution:
    def isValidBST(self, root: Optional[TreeNode]) -> bool:
        def is_valid_bst(node, min_val, max_val):
            if not node:
                return True
            if node.val <= min_val or max_val <= node.val:
                return False
            return is_valid_bst(node.left, min_val, node.val) and is_valid_bst(node.right, node.val, max_val) 
        
        return is_valid_bst(root, -math.inf, math.inf)
#+END_SRC

I originally did an uglier version of the same algorithm:

#+BEGIN_SRC python
# Definition for a binary tree node.
# class TreeNode:
#     def __init__(self, val=0, left=None, right=None):
#         self.val = val
#         self.left = left
#         self.right = right
def isValidBSTAux(root):
    if root.left:
        is_valid_left, min_left, max_left = isValidBSTAux(root.left)
    else:
        is_valid_left, min_left, max_left = True, math.inf, -math.inf
    
    if root.right:
        is_valid_right, min_right, max_right = isValidBSTAux(root.right)
    else:
        is_valid_right, min_right, max_right = True, math.inf, -math.inf
    
    return max_left < root.val and root.val < min_right and is_valid_left and is_valid_right, min([min_left, min_right, root.val]), max([max_left, max_right, root.val])

class Solution:
    def isValidBST(self, root: Optional[TreeNode]) -> bool:
        if not root:
            return True
        
        return isValidBSTAux(root)[0]
#+END_SRC

The idea behind the code is very similar although this algorithm does not finish early and traverses the tree completely.
** [[https://leetcode.com/problems/number-of-islands/][200. Number of Islands]]
They are asking to understand what is the number of connected components made up of 1s. To solve this problem I used a set that contains all 1s and then extract a random one for that set to traverse the component that that 1 belongs to. While traversing the grid we remove ones from the the set.

#+BEGIN_SRC python
def get_neighbors(current, grid):
    ret = []
    if current[0] > 0:
        ret.append((current[0]-1, current[1]))
    if current[0] + 1 < len(grid):
        ret.append((current[0]+1, current[1]))
    if current[1] > 0:
        ret.append((current[0], current[1]-1))
    if current[1] + 1 < len(grid[0]): # n, m >= 1
        ret.append((current[0], current[1]+1))
    return ret

def discover_connected_component(point, q, grid):
    stack = [point]

    while stack:
        current = stack.pop()
        for neighbor in get_neighbors(current, grid):
            if neighbor in q:
                stack.append(neighbor)
                q.remove(neighbor)

class Solution:
    def numIslands(self, grid: List[List[str]]) -> int:
        ret = 0
        ones = set()
        for i, row in enumerate(grid):
            for j, val in enumerate(row):
                if grid[i][j] == "1":
                    ones.add((i,j))

        while ones:
            point = ones.pop()
            discover_connected_component(point, ones, grid)
            ret += 1
        
        return ret
#+END_SRC
