#+title: BFS traversal
In this sort of problems we need to prioritize exploring th tree in breadth instead of in depth that can be done using recursion or a queue (i.e. LIFO)
* Problems:
** [[https://leetcode.com/problems/01-matrix/description/][01 Matrix]]

The first solution I came up with is exploring the matrix up to n+m times and substracting the ones into an auxiliary matrix this is a quadratic algorithm over the size of the input.

It looked like this:

#+BEGIN_SRC python
# Example 4:
# 1 1 1
# 1 1 1
# 1 1 0
# 
# 1 1 1 # 1 1 1 
# 1 1 0 # 1 1 1
# 1 0 0 # 1 1 0
#
# 1 1 0 # 2 2 2 
# 1 0 0 # 2 2 1
# 0 0 0 # 2 1 0
#
# 1 0 0 # 3 3 2 
# 0 0 0 # 3 2 1
# 0 0 0 # 2 1 0
#
# 0 0 0 # 4 3 2 
# 0 0 0 # 3 2 1
# 0 0 0 # 2 1 0
#+END_SRC

I then thought that we could do a breadth-first traversal starting from the elements of the matrix that were 0. Every processed node will store 1 + the minimum value of their processed neighbours.

#+BEGIN_SRC python
# queue = [(2,2)]
# 1 1 1 # X X X 
# 1 1 1 # X X X
# 1 1 0 # X X 0
# queue = [(2,2)]
# 1 1 1 # X X X 
# 1 1 1 # X X X
# 1 1 0 # X X 0
# queue = [(1,2), (2, 1)]
# 1 1 1 # X X X 
# 1 1 1 # X X 1
# 1 1 0 # X X 0
# queue = [(1, 1), (0, 2), ]
# 1 1 1 # X X X 
# 1 1 1 # X X 1
# 1 1 0 # X 1 0
#+END_SRC

The reason we use breadth-first is that we want to explore the neighbours of all 0s to mark them as being distance 1 before we continue diving deeper into the tree. Using a queue as the auxiliary data structure guarantees that all points at distance 1 from a 0 will be explored before all points at distance 2 and so on and so forth.

#+BEGIN_SRC python
class Solution:
    def neighbourhood(self, mat, i, j):
        n = len(mat)
        m = len(mat[0])

        ret = []

        if i > 0:
            ret.append((i-1,j))
        if i + 1 < n:
            ret.append((i+1,j))
        if j > 0:
            ret.append((i,j-1))
        if j + 1 < m:
            ret.append((i,j+1))

        return ret

    def updateMatrix(self, mat: List[List[int]]) -> List[List[int]]:
        ret = []
        visited = []
        discovered = []

        # I initialize the auxiliary data structures.
        for row in mat:
            ret.append([math.inf for elem in row])
            visited.append([False for elem in row])
            discovered.append([False  for elem in row])

        # I create a queue and prepopulate it with all 0s
        queue = []
        for i, row in enumerate(mat):
            for j, elem in enumerate(row):
                if elem == 0:
                    queue.append((i,j))
                    discovered[i][j] = True
        
        # I traverse the matrix once and update ret[i][j] to the minimum of it's one value or 1 + the value of another visited neighbour
        while queue:
            i, j = queue.pop(0)
            visited[i][j] = True
            if mat[i][j] == 0:
                ret[i][j] = 0
            for a, b in self.neighbourhood(mat, i, j):
                if visited[a][b]:
                    ret[i][j] = min(ret[i][j], ret[a][b]+1)
                elif not discovered[a][b]:
                    queue.append((a, b))
                    discovered[a][b] = True
        return ret
#+END_SRC
** [[https://leetcode.com/problems/binary-tree-level-order-traversal/description/][Binary Tree Level Order Traversal]]
Very simple BFS traversal we add a height to the node that we are visiting at each point if the level/height changes we push the collection of elements in the prior level and start a new one.

#+BEGIN_SRC python
# Definition for a binary tree node.
# class TreeNode:
#     def __init__(self, val=0, left=None, right=None):
#         self.val = val
#         self.left = left
#         self.right = right
class Solution:
    def levelOrder(self, root: Optional[TreeNode]) -> List[List[int]]:
        if not root:
            return []

        queue = [(root, 0)]
        levels = []
        current_level = []

        while queue:
            node, height = queue.pop(0)

            if node.left:
                queue.append((node.left, height+1))
            if node.right:
                queue.append((node.right, height+1))

            if height > len(levels):
                levels.append(current_level)
                current_level = []
            current_level.append(node.val)
        
        if current_level:
            levels.append(current_level)
        
        return levels
#+END_SRC
** [[https://leetcode.com/problems/clone-graph/description/][Clone Graph]]
In this problem we will traverse a graph using BFS and initialize another graph at the same time that will be a deep copy of the initial graph.

#+BEGIN_SRC python
"""
# Definition for a Node.
class Node:
    def __init__(self, val = 0, neighbors = None):
        self.val = val
        self.neighbors = neighbors if neighbors is not None else []
"""
from typing import Optional
class Solution:
    def cloneGraph(self, node: Optional['Node']) -> Optional['Node']:
        cloned_vertices = dict()

        if not node:
            return None

        # Using a queue for BFS traversal
        queue = [node]
        cloned_vertices[node.val] = Node(val=node.val)
    
        while queue:
            current_node = queue.pop(0)
            for neighbor in current_node.neighbors:
                if neighbor.val not in cloned_vertices:
                    cloned_vertices[neighbor.val] = Node(val=neighbor.val)
                    queue.append(neighbor)
                cloned_vertices[current_node.val].neighbors.append(cloned_vertices[neighbor.val])
        
        return cloned_vertices[node.val]
#+END_SRC

I also submitted the DFS version of the algorithm and worked.
** [[https://leetcode.com/problems/rotting-oranges/][994. Rotting Oranges]]
We are going to peform a variation of the BFS. We start with the rotten tomatoes in the grid and store healthy tomatos in a set. At every iteration we try to rot nearby tomatos of those that were rotten at that minute, if we are successful we add another minute and try again in other case we either return the number of minutes that have passed or -1 if there are stil healthy tomatos.

#+BEGIN_SRC python
def get_neighbors(current, grid):
    ret = []
    if current[0] > 0:
        ret.append((current[0]-1, current[1]))
    if current[0] + 1 < len(grid):
        ret.append((current[0]+1, current[1]))
    if current[1] > 0:
        ret.append((current[0], current[1]-1))
    if current[1] + 1 < len(grid[0]): # n, m >= 1
        ret.append((current[0], current[1]+1))
    return ret

def next_round_of_rotten_oranges(queue, good_oranges, grid):
    new_rotten_oranges = []
    for rotten_pos in queue:
        neighbors = get_neighbors(rotten_pos, grid)
        for i, j in neighbors:
            if grid[i][j] == 1:
                new_rotten_oranges.append((i,j))
                grid[i][j] = 2
                good_oranges.remove((i,j))
    return new_rotten_oranges

class Solution:
    def orangesRotting(self, grid: List[List[int]]) -> int:
        minutes = 0
        rotten_queue = []
        good_oranges = set()

        for i, row in enumerate(grid):
            for j, elem in enumerate(row):
                if elem == 2:
                    rotten_queue.append((i,j))
                if elem == 1:
                    good_oranges.add((i,j))
        
        while rotten_queue:
            rotten_queue = next_round_of_rotten_oranges(rotten_queue, good_oranges, grid)
            if rotten_queue:
                minutes += 1
        
        if good_oranges:
            return -1

        return minutes
#+END_SRC

