#+title: Binary search
These are problems that involve efficiently finding the insertion place of an element in an array using the binary search algorithm. Other times a similar reasoning can be applied over an array where some of the elements in the array fulfill a boolean predicate anb other's don't.

The binary search that I use is the following:

#+BEGIN_SRC python
    def binarySearch(self, list, elem):
        l, r = 0, len(list)
        while l + 1 < r:
            mid = (l+r)//2
            if list[mid] <= elem:
                l = mid
            else:
                r = mid
        return l
#+END_SRC

Common pitfall: calculating mid = l+r//2 (division has precedence over sum).
* Problems:
** [[https://leetcode.com/problems/insert-interval/description/][57. Insert Interval]]
This was a very painful problem!

I solved it by flattening the intervals and then found what were the positions that a binary search gave over the intervals array.

Then I came up with rules on how to build the array that will be returned.

I spent >1h solving it not sure if this is the best way of showing if I know how to program or not...

I was the fastest response in leetcode. Sth. to be proud of I guess.

#+BEGIN_SRC python
class Solution:
    def binarySearch(self, list, elem):
        l, r = 0, len(list)
        while l + 1 < r:
            mid = (l+r)//2
            if list[mid] <= elem:
                l = mid
            else:
                r = mid
        return l

    def insert(self, intervals: List[List[int]], newInterval: List[int]) -> List[List[int]]:
        if not intervals:
            return [newInterval]

        flattened = [x_n for interval in intervals for x_n in interval]

        start_new_interval, end_new_interval = newInterval

        position_start_new_interval = self.binarySearch(flattened, start_new_interval)
        position_end_new_interval = self.binarySearch(flattened, end_new_interval)

        ret = []

        # If start_i < end_i <= start_new_interval
        if position_start_new_interval % 2:
            # If end_i < start_new_interval
            if flattened[position_start_new_interval] != start_new_interval:
                ret += flattened[:position_start_new_interval+1] # -> ret += [[start_0, end_0],...,[start_i, end_i]]
            else:
                ret += flattened[:position_start_new_interval-1] # -> ret += [[start_0, end_0],...,[start_i-1, end_i-1]]
                start_new_interval = flattened[position_start_new_interval-1] # -> start_new_interval = start_i
        # If start_new_interval < end_i
        else:
            ret += flattened[:position_start_new_interval]  # -> ret += [[start_0, end_0],...,[start_i-1, end_i-1]]
            # If start_i < start_new_interval 
            if start_new_interval > flattened[position_start_new_interval]:
                start_new_interval = flattened[position_start_new_interval] # -> start_new_interval = start_i

        # If start_j < end_j <= end_new_interval        
        if position_end_new_interval % 2:
            ret += [start_new_interval, end_new_interval] # -> ret += [start_new_interval, end_new_interval]
            ret += flattened[position_end_new_interval+1:] # -> ret += [[start_j+1, end_j+1], ...]
        # If end_new_interval < end_j
        else:
            # If end_new_interval < start_j
            if end_new_interval < flattened[position_end_new_interval]:
                ret += [start_new_interval, end_new_interval] + flattened[position_end_new_interval:] # -> ret += [start_new_interval, end_new_interval] + [[start_j,end_j], ...]
            # If start_j <= end_new_interval < end_j
            else:
                ret += [start_new_interval, flattened[position_end_new_interval + 1]] + flattened[position_end_new_interval + 2:] # -> ret += [start_new_interval, end_j], [[start_j+1, end_j+1], ...]
    
        return [[start_i, end_i] for start_i, end_i in zip(ret[::2], ret[1::2])]
#+END_SRC
** [[https://leetcode.com/problems/search-in-rotated-sorted-array/description/][33. Search in Rotated Sorted Array]]
To solve this problem the first thing you need to notice is that one can retrieve the exact point at which the array is divided into two sorted arrays using a binary search argument. Lets say that m is the minimum value in the array and M is the maximum value in the array since the original array was a non decreasing array composed only of different numbers we would have that before the rotation the array will look like this:
m, y0, y1, y2, ..., M
After the rotation we would have:
x0, ..., M, m, ..., xn-1
where x0, ..., M and m, ..., xn-1 are non decreasing arrays.
We can return the exact index at which M is sitting using the following algorithm. We follow a binary search solution only that in this case if x[l] <= x[mid] we move left to mid and the opposite in the other case. What we have is that in log(n) steps we would get index of M. We've called this method get_partition_index 
#+BEGIN_SRC python
def find_partition(nums):
    left = 0
    right = len(nums)

    while left + 1 < right:
        mid = (left + right)//2
        if nums[left] <= nums[mid]:
            left = mid
        else:
            right = mid
    
    return left
#+END_SRC
NOTE: Notice that the k used in the problem statement is n - find_partition(nums).
Then once we know the index at which the partition is we just need to do a regular binary search over the subarray that is sorted:
#+BEGIN_SRC python
class Solution:
    def search(self, nums: List[int], target: int) -> int:
        index = find_partition(nums)
        if nums[0] <= target and target <= nums[index]:
            left = 0
            right = index + 1
        else:
            left = index + 1
            right = len(nums)
        
        while left + 1 < right:
            mid = (left + right)//2
            if nums[mid] <= target:
                left = mid
            else:
                right = mid
        
        if left >= len(nums) or nums[left] != target:
            return -1
        return left
#+END_SRC



